config/routes.rb
Rails.application.routes.draw do
  resources :clients do
    resources :inspections
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :inspections
end

app/models/inspection.rb
class Inspection < ApplicationRecord
  belongs_to :client
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :street, :number, :zipcode, :city, :contact_name, :contact_phone, :contact_email)
    end
end

app/controllers/inspections_controller.rb
class InspectionsController < ApplicationController
  before_action :set_client
  before_action :set_inspection, only: [:show, :edit, :update, :destroy]

  # GET clients/1/inspections
  def index
    @inspections = @client.inspections
  end

  # GET clients/1/inspections/1
  def show
  end

  # GET clients/1/inspections/new
  def new
    @inspection = @client.inspections.build
  end

  # GET clients/1/inspections/1/edit
  def edit
  end

  # POST clients/1/inspections
  def create
    @inspection = @client.inspections.build(inspection_params)

    if @inspection.save
      redirect_to([@inspection.client, @inspection], notice: 'Inspection was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT clients/1/inspections/1
  def update
    if @inspection.update_attributes(inspection_params)
      redirect_to([@inspection.client, @inspection], notice: 'Inspection was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE clients/1/inspections/1
  def destroy
    @inspection.destroy

    redirect_to client_inspections_url(@client)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:client_id])
    end

    def set_inspection
      @inspection = @client.inspections.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def inspection_params
      params.require(:inspection).permit(:project_number, :project_name, :inspection_date, :inspection_address_street, :inspection_address_number, :inspection_address_zipcode, :inspection_address_city, :contact_person_name, :contact_person_phone, :contact_person_email, :report_compiler, :release_date, :approved, :building_image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/inspections_helper.rb
module InspectionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :zipcode %>
    <%= form.text_field :zipcode %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :contact_name %>
    <%= form.text_field :contact_name %>
  </div>

  <div class="field">
    <%= form.label :contact_phone %>
    <%= form.text_field :contact_phone %>
  </div>

  <div class="field">
    <%= form.label :contact_email %>
    <%= form.text_field :contact_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Klanten</h1>
<div class="card">
  <ul class="list-group list-group-flush">
    <% @clients.each do |client| %>
      <li class="list-group-item d-flex bd-highlight">
        <div class="flex-grow-1 bd-highlight">
          <h5 class="card-title mb-0"><%= client.name %></h5>
          <small class="card-text">
            <%= client.street %>
            <%= client.number %>,
            <%= client.zipcode %>,
            <%= client.city %>
          </small>
        </div>
        <div class="bd-highlight align-self-center">
          <%= link_to 'Show', client, class: 'btn btn-sm btn-outline-primary' %>
        </div>
      </li>
    <% end %>
  </div>
<br>

<div class="float-right">
  <%= link_to 'New Client', new_client_path, class: 'btn btn-primary' %>
</div>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Street:</strong>
  <%= @client.street %>
</p>

<p>
  <strong>Number:</strong>
  <%= @client.number %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @client.zipcode %>
</p>

<p>
  <strong>City:</strong>
  <%= @client.city %>
</p>

<p>
  <strong>Contact name:</strong>
  <%= @client.contact_name %>
</p>

<p>
  <strong>Contact phone:</strong>
  <%= @client.contact_phone %>
</p>

<p>
  <strong>Contact email:</strong>
  <%= @client.contact_email %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/inspections/_form.html.erb
<%= form_for([@inspection.client, @inspection]) do |f| %>
  <% if @inspection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inspection.errors.count, "error") %> prohibited this inspection from being saved:</h2>

      <ul>
      <% @inspection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_number %><br />
    <%= f.number_field :project_number %>
  </div>
  <div class="field">
    <%= f.label :project_name %><br />
    <%= f.text_field :project_name %>
  </div>
  <div class="field">
    <%= f.label :inspection_date %><br />
    <%= f.datetime_select :inspection_date %>
  </div>
  <div class="field">
    <%= f.label :inspection_address_street %><br />
    <%= f.text_field :inspection_address_street %>
  </div>
  <div class="field">
    <%= f.label :inspection_address_number %><br />
    <%= f.text_field :inspection_address_number %>
  </div>
  <div class="field">
    <%= f.label :inspection_address_zipcode %><br />
    <%= f.text_field :inspection_address_zipcode %>
  </div>
  <div class="field">
    <%= f.label :inspection_address_city %><br />
    <%= f.text_field :inspection_address_city %>
  </div>
  <div class="field">
    <%= f.label :contact_person_name %><br />
    <%= f.text_field :contact_person_name %>
  </div>
  <div class="field">
    <%= f.label :contact_person_phone %><br />
    <%= f.text_field :contact_person_phone %>
  </div>
  <div class="field">
    <%= f.label :contact_person_email %><br />
    <%= f.text_field :contact_person_email %>
  </div>
  <div class="field">
    <%= f.label :report_compiler %><br />
    <%= f.text_field :report_compiler %>
  </div>
  <div class="field">
    <%= f.label :release_date %><br />
    <%= f.datetime_select :release_date %>
  </div>
  <div class="field">
    <%= f.label :approved %><br />
    <%= f.check_box :approved %>
  </div>
  <div class="field">
    <%= f.label :building_image %><br />
    <%= f.text_field :building_image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inspections/edit.html.erb
<h1>Editing inspection</h1>

<%= render 'form' %>

<%= link_to 'Show', [@inspection.client, @inspection] %> |
<%= link_to 'Back', client_inspections_path(@inspection.client) %>

app/views/inspections/index.html.erb
<h1>Listing inspections</h1>

<table>
  <tr>
    <th>Project number</th>
    <th>Project name</th>
    <th>Inspection date</th>
    <th>Inspection address street</th>
    <th>Inspection address number</th>
    <th>Inspection address zipcode</th>
    <th>Inspection address city</th>
    <th>Contact person name</th>
    <th>Contact person phone</th>
    <th>Contact person email</th>
    <th>Report compiler</th>
    <th>Release date</th>
    <th>Approved</th>
    <th>Building image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @inspections.each do |inspection| %>
  <tr>
    <td><%= inspection.project_number %></td>
    <td><%= inspection.project_name %></td>
    <td><%= inspection.inspection_date %></td>
    <td><%= inspection.inspection_address_street %></td>
    <td><%= inspection.inspection_address_number %></td>
    <td><%= inspection.inspection_address_zipcode %></td>
    <td><%= inspection.inspection_address_city %></td>
    <td><%= inspection.contact_person_name %></td>
    <td><%= inspection.contact_person_phone %></td>
    <td><%= inspection.contact_person_email %></td>
    <td><%= inspection.report_compiler %></td>
    <td><%= inspection.release_date %></td>
    <td><%= inspection.approved %></td>
    <td><%= inspection.building_image %></td>
    <td><%= link_to 'Show', [inspection.client, inspection] %></td>
    <td><%= link_to 'Edit', edit_client_inspection_path(inspection.client, inspection) %></td>
    <td><%= link_to 'Destroy', [inspection.client, inspection], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Inspection', new_client_inspection_path(params[:client_id]) %>

app/views/inspections/new.html.erb
<h1>New inspection</h1>

<%= render 'form' %>

<%= link_to 'Back', client_inspections_path(@inspection.client) %>

app/views/inspections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Project number:</b>
  <%= @inspection.project_number %>
</p>

<p>
  <b>Project name:</b>
  <%= @inspection.project_name %>
</p>

<p>
  <b>Inspection date:</b>
  <%= @inspection.inspection_date %>
</p>

<p>
  <b>Inspection address street:</b>
  <%= @inspection.inspection_address_street %>
</p>

<p>
  <b>Inspection address number:</b>
  <%= @inspection.inspection_address_number %>
</p>

<p>
  <b>Inspection address zipcode:</b>
  <%= @inspection.inspection_address_zipcode %>
</p>

<p>
  <b>Inspection address city:</b>
  <%= @inspection.inspection_address_city %>
</p>

<p>
  <b>Contact person name:</b>
  <%= @inspection.contact_person_name %>
</p>

<p>
  <b>Contact person phone:</b>
  <%= @inspection.contact_person_phone %>
</p>

<p>
  <b>Contact person email:</b>
  <%= @inspection.contact_person_email %>
</p>

<p>
  <b>Report compiler:</b>
  <%= @inspection.report_compiler %>
</p>

<p>
  <b>Release date:</b>
  <%= @inspection.release_date %>
</p>

<p>
  <b>Approved:</b>
  <%= @inspection.approved %>
</p>

<p>
  <b>Building image:</b>
  <%= @inspection.building_image %>
</p>


<%= link_to 'Edit', edit_client_inspection_path(@inspection.client, @inspection) %> |
<%= link_to 'Back', client_inspections_path(@inspection.client) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LviExamination</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark" style="background-color: #ef2e24;">
      <%= link_to 'KIV Noord', root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to 'Home', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Klanten', clients_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </nav>
    <main role="main" class="container">
      <%= yield %>
    </main>
  </body>
</html>